jje/config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new",      as: 'sign_in' # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    get "/edit_account" => "devise/registrations#edit", as: "edit_account"
    get "/sign_out"=> "devise/sessions#destroy",  as: 'sign_out'
  end

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  # contains only digits
  id_cnstrt = /\d+/
  # contains at least one non-digit
  nonid_cnst = /[^\/]*[^\d\/][^\/]*/


  root  'static_pages#Home'
  get   '/Home',          to: redirect('/'),            as: :home


  # Authorization
  get   '/auth/login',    to: 'static_pages#login'
  post  '/auth/login',    to: 'sessions#create',        as: 'login'
  get   '/auth/logout',   to: 'sessions#destroy',       as: 'logout'
  get   '/auth/register', to: 'static_pages#register',  as: 'register'
  post  '/auth/register', to: 'users#create',           as: :create_user
  get   '/auth/failure',  to: redirect('/auth/login?failed')
  get   '/auth/:provider/callback',  to: 'sessions#create'

  get   '/search',        to: 'static_pages#search',    as: :search

  # Subsection Homepages
  get   '/problems',    to: 'static_pages#problems',    as: :problems
  get   '/users',       to: 'static_pages#users',       as: :users
  get   '/tournaments', to: 'static_pages#tournaments', as: :tournaments

  # Problems Subsection
  get   '/problems/new',                to: 'problems#new',                           as: :new_problem
  post  '/problems',                    to: 'problems#create',                        as: :create_problem
  get   '/problems/statistics',         to: 'problems#stats',                         as: :stats_problem
  get   '/problems/:id',                to: 'problems#show',          id: id_cnstrt,  as: :problem
  get   '/problems/:id/edit',           to: 'problems#edit',          id: id_cnstrt,  as: :edit_problem
  put   '/problems/:id',                to: 'problems#update',        id: id_cnstrt,  as: :update_problem
  get   '/problems/:id/submit/',        to: 'problems#showUpload',    id: id_cnstrt,  as: :upload_problem
  post  '/problems/:id/submit/code',    to: 'problems#uploadCode',    id: id_cnstrt,  as: :uploadCode_problem
  post  '/problems/:id/submit/output',  to: 'problems#uploadOutput',  id: id_cnstrt,  as: :uploadOutput_problem
  get   '/problems/:id/inputs/*flname', to: 'problems#downloadInput', id: id_cnstrt,  as: :downloadInput_problem, format: false

  # Users Subsection
  get   '/users/:id',                   to: 'users#show',             id: id_cnstrt,  as: :user
  get   '/users/:id/edit',              to: 'users#edit',             id: id_cnstrt,  as: :edit_user
  patch '/users/:id',                   to: 'users#update',           id: id_cnstrt,  as: :update_user
  get   '/users/:id/submissions',       to: 'users#submissions',      id: id_cnstrt,  as: :user_submissions
  get   '/users/:user_id/submissions/:problem_id/:timestamp', to: 'user_submissions#show',  user_id: id_cnstrt, problem_id: id_cnstrt, as: :user_submission
  match '/users/:username/(*all)',      to: 'users#name_to_id', username: nonid_cnst, via: [:get, :put]

  # Tournaments Subsection
  get   '/tournaments/new',             to: 'tournaments#new',                        as: :new_tournament
  post  '/tournaments',                 to: 'tournaments#create',                     as: :create_tournament
  get   '/tournaments/:id',             to: 'tournaments#show',     id: id_cnstrt,    as: :tournament
  get   '/tournaments/:id/edit',        to: 'tournaments#edit',     id: id_cnstrt,    as: :edit_tournament
  patch   '/tournaments/:id',             to: 'tournaments#update',   id: id_cnstrt,    as: :update_tournament
  get   '/tournaments/:id/statistics',  to: 'tournaments#stats',    id: id_cnstrt,    as: :stats_tournament
  get   '/tournaments/:id/join',        to: 'tournaments#join',     id: id_cnstrt,    as: :join_tournament

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

jje/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]
  self.primary_key = 'user_id'
  
  has_many :submissions, class_name: 'UserSubmission'

  def self.from_omniauth(access_token)
      data = access_token.info
      user = User.where(:email => data["email"]).first

      unless user
          user = User.create(display_name: data["name"],
              email: data["email"],
              password: Devise.friendly_token[0,20]
          )
      end
      user
  end
end

jje/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"].except(:extra) #Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

jje/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :submissions]

  def index
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @tournaments = Tournament.joins(:competes_ins).where(["user_id = %i", @user.user_id])
    @solves = Problem.joins(:submissions).where(["user_id = %i and solved", @user.user_id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/1/edit
  def edit
    unless @user == current_user or (user_signed_in? and current_user.admin) then
      redirect_to @user, flash: {error: "Can only edit your own user!"}
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/1/submissions
  def submissions
    @submissions = @user.submissions
  end

  # *VERB* /users/:username/(*all)  =>  *VERB* /users/:id/:all
  def name_to_id
      @user = User.where(display_name: params[:username]).first
      if @user
        redirect_to "/users/#{@user.user_id}/#{params[:all]}"
      else
        raise ActiveRecord::RecordNotFound
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:display_name, :university, :company)
    end
end

jje/app/helpers/users_helper.rb
module UsersHelper
end

jje/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :display_name %>
    <%= f.text_field :display_name %>
    <%= f.label :university %>
    <%= f.text_field :university %>
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jje/app/views/users/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

jje/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

jje/app/views/users/show.html.erb
<h1><%= @user.display_name %>'s Profile</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th> Profile Field </th>
            <th>
            Value
            </th>
        </tr>
    </thead>
    <tbody
        <tr>
            <td> Name </td>
            <td><%= @user.display_name %></td>
        </tr>
        <tr>
            <td> Score </td>
            <td><%= @user.score %></td>
        </tr>
        <tr>
            <td> University </td>
            <td><%= @user.university %></td>
        </tr>
        <tr>
            <td> Company </td>
            <td><%= @user.company %></td>
        </tr>
        <tr>
        	<td> Date Created </td>
        	<td><%=@user.created_at %></td>
        </tr>
    </tbody> 
</table>

<% if user_signed_in? and (@user == current_user or current_user.admin) then %>
    <%= button_to 'Edit Profile', edit_user_path(@user), :method => :get %>
<%end%>

<h3>Competing in</h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Tournament</th>
        </tr>
    </thead>
    <tbody>
        <% @tournaments.each do |tourn| %>
        <tr>
            <td><%= link_to(tourn.name, tournament_path(tourn.tournament_id)) %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<h3>Solved Problems</h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Point Value</th>
        </tr>
    </thead>
    <tbody>
        <% @solves.each do |prob| %>
        <tr>
            <td><%= link_to(prob.name, problem_path(prob.problem_id)) %></td>
            <td><%= prob.score %></td>

        </tr>
        <% end %>
    </tbody>
</table>

<% if user_signed_in? and (@user == current_user or current_user.admin) then %>
    <%= button_to "All Submissions", user_submissions_path(@user.user_id), :method => :get %>
<%end%>

<%= button_to "Back to All Users", users_path, :method => :get %>

jje/app/views/users/submissions.html.erb
<h1><%= link_to(@user.display_name, @user) %>'s Submissions</h1>

<article>
	<section>
		<h3>All Submissions</h3>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Problem ID</th>
					<th>Problem</th>
					<th>Timestamp</th>
					<th>Solved?</th>
					<th>Language</th>
					<th>Runtime</th>
					<th>View</th>
				</tr>
			</thead>
			<tbody>
				<% @submissions.each do |subm| %>
				<tr class="<%=(subm.solved ? 'success' : (subm.solved == nil ? '' : 'danger'))%>">
					<td><%= subm.problem_id %></td>
					<td><%= link_to(Problem.find(subm.problem_id).name, problem_path(subm.problem_id)) %></td>
					<td><%= subm.timestamp.getlocal.to_s(:long) %></td>
					<td><%= (subm.solved ? "Solved" : (subm.solved == nil ? "" : "Failed")) %></td>
					<td><%= subm.language %></td>
					<td><%= subm.runtime %></td>
					<td><%= link_to("View Submission", user_submission_path(subm.user_id, subm.problem_id, subm.timestamp)) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</section>
</article>