jje/config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new",      as: 'sign_in' # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    get "/edit_account" => "devise/registrations#edit", as: "edit_account"
    get "/sign_out"=> "devise/sessions#destroy",  as: 'sign_out'
  end

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  # contains only digits
  id_cnstrt = /\d+/
  # contains at least one non-digit
  nonid_cnst = /[^\/]*[^\d\/][^\/]*/


  root  'static_pages#Home'
  get   '/Home',          to: redirect('/'),            as: :home


  # Authorization
  get   '/auth/login',    to: 'static_pages#login'
  post  '/auth/login',    to: 'sessions#create',        as: 'login'
  get   '/auth/logout',   to: 'sessions#destroy',       as: 'logout'
  get   '/auth/register', to: 'static_pages#register',  as: 'register'
  post  '/auth/register', to: 'users#create',           as: :create_user
  get   '/auth/failure',  to: redirect('/auth/login?failed')
  get   '/auth/:provider/callback',  to: 'sessions#create'

  get   '/search',        to: 'static_pages#search',    as: :search

  # Subsection Homepages
  get   '/problems',    to: 'static_pages#problems',    as: :problems
  get   '/users',       to: 'static_pages#users',       as: :users
  get   '/tournaments', to: 'static_pages#tournaments', as: :tournaments

  # Problems Subsection
  get   '/problems/new',                to: 'problems#new',                           as: :new_problem
  post  '/problems',                    to: 'problems#create',                        as: :create_problem
  get   '/problems/statistics',         to: 'problems#stats',                         as: :stats_problem
  get   '/problems/:id',                to: 'problems#show',          id: id_cnstrt,  as: :problem
  get   '/problems/:id/edit',           to: 'problems#edit',          id: id_cnstrt,  as: :edit_problem
  put   '/problems/:id',                to: 'problems#update',        id: id_cnstrt,  as: :update_problem
  get   '/problems/:id/submit/',        to: 'problems#showUpload',    id: id_cnstrt,  as: :upload_problem
  post  '/problems/:id/submit/code',    to: 'problems#uploadCode',    id: id_cnstrt,  as: :uploadCode_problem
  post  '/problems/:id/submit/output',  to: 'problems#uploadOutput',  id: id_cnstrt,  as: :uploadOutput_problem
  get   '/problems/:id/inputs/*flname', to: 'problems#downloadInput', id: id_cnstrt,  as: :downloadInput_problem, format: false

  # Users Subsection
  get   '/users/:id',                   to: 'users#show',             id: id_cnstrt,  as: :user
  get   '/users/:id/edit',              to: 'users#edit',             id: id_cnstrt,  as: :edit_user
  patch '/users/:id',                   to: 'users#update',           id: id_cnstrt,  as: :update_user
  get   '/users/:id/submissions',       to: 'users#submissions',      id: id_cnstrt,  as: :user_submissions
  get   '/users/:user_id/submissions/:problem_id/:timestamp', to: 'user_submissions#show',  user_id: id_cnstrt, problem_id: id_cnstrt, as: :user_submission
  match '/users/:username/(*all)',      to: 'users#name_to_id', username: nonid_cnst, via: [:get, :put]

  # Tournaments Subsection
  get   '/tournaments/new',             to: 'tournaments#new',                        as: :new_tournament
  post  '/tournaments',                 to: 'tournaments#create',                     as: :create_tournament
  get   '/tournaments/:id',             to: 'tournaments#show',     id: id_cnstrt,    as: :tournament
  get   '/tournaments/:id/edit',        to: 'tournaments#edit',     id: id_cnstrt,    as: :edit_tournament
  patch   '/tournaments/:id',             to: 'tournaments#update',   id: id_cnstrt,    as: :update_tournament
  get   '/tournaments/:id/statistics',  to: 'tournaments#stats',    id: id_cnstrt,    as: :stats_tournament
  get   '/tournaments/:id/join',        to: 'tournaments#join',     id: id_cnstrt,    as: :join_tournament

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

jje/app/models/problem.rb
class Problem < ApplicationRecord
  self.primary_key = 'problem_id'
  has_many :keywords, :class_name => 'ProblemKeyword', dependent: :destroy
  has_many :tags, :class_name => 'ProblemTag', dependent: :destroy
  has_many :submissions, class_name: 'UserSubmission', dependent: :destroy
  has_many :tournaments, through: :contains
  has_many :contains
  
  def to_s
    "Name: #{self.name}, ID: #{self.problem_id}"
  end      

end

jje/app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_problem, only: [:show, :edit, :update, :showUpload, :uploadCode, :uploadOutput, :downloadInput]
  require 'fileutils'

  # GET /problems/new
  def new
    unless current_user.admin?
      redirect_to :tournaments, flash: {error: 'Only administrators can create new problems.'}
    end
    @problem = Problem.new
  end

  # POST /problems
  def create
    unless current_user.admin?
      redirect_to :problems, flash: {error: 'Only administrators can create new problems.'}
    end
    keywords = params[:keywords][:allkeywords].split
    tags = params[:tags][:alltags].split
    # TODO: sanitize keywords/tags
    input_files = params[:files][:input]
    output_files = params[:files][:output]

    @problem = Problem.new(problem_params)
    if @problem.save
      keywords.each do |kw|
        @problem.keywords.create(keyword: kw)
      end
      tags.each do |tag|
        @problem.tags.create(tag: tag)
      end

      basepath = Rails.root.join("problems", "#{@problem.problem_id}")
      Dir.mkdir(basepath)
      Dir.mkdir(basepath.join('input'))
      Dir.mkdir(basepath.join('output'))
      input_files.each do |upfile|
        File.open(basepath.join('input', upfile.original_filename), 'wb') do |file|
          file.write(upfile.read)
        end
      end
      output_files.each do |upfile|
        File.open(basepath.join('output', upfile.original_filename), 'wb') do |file|
          file.write(upfile.read)
        end
      end

      redirect_to @problem, flash: {success: 'Problem created!'}
    else
      redirect_to :new_problem, flash: {error: "Failed to create problem: #{@problem.errors.full_messages}"}
    end
  end

  # GET /problems/:id/edit
  def edit
    unless current_user.admin?
      redirect_to :problems, flash: {error: 'Only administrators can edit problems.'}
    end
    @keywordstring = @problem.keywords.collect(&:keyword).join(' ')
    @tagstring = @problem.tags.collect(&:tag).join(' ')
  end

  # PUT /problems/:id
  def update
    unless current_user.admin?
      redirect_to :problems, flash: {error: 'Only administrators can create new problems.'}
    end
    keywords = params[:keywords][:allkeywords].split
    tags = params[:tags][:alltags].split
    # TODO: sanitize keywords/tags

    if @problem.update(problem_params)
      @problem.keywords.clear
      keywords.each do |kw| @problem.keywords.create(keyword: kw) end
      @problem.tags.clear
      tags.each do |tag| @problem.tags.create(tag: tag) end

      redirect_to @problem, flash: {success: 'Problem updated!'}
    else
      redirect_to @problem, flash: {error: "Failed to update problem: #{@problem.errors.full_messages}"}
    end
  end

  # GET /problems/statistics
  def stats
    @problems = Problem.all
  end

  # GET /problems/:id
  def show
    @input_path = Rails.root.join("problems","#{@problem.problem_id}", "input")
    @solves = UserSubmission.joins(:user).where(["problem_id = %i and solved", @problem.problem_id])
    .order("user_submissions.timestamp").limit(1)
  end

  # GET /problems/:id/submit
  def showUpload
  end

  # POST /problems/:id/submit/code
  def uploadCode
    uploaded_lang = params[:language]
    uploaded_main = params[:main]
    uploaded_supp = params[:support]

    # TODO: handle submission
    sandhome = "/home/jjeuser"
    probnum = @problem.problem_id
    destpath = "users/#{current_user.user_id}/submissions/#{probnum}"
    probpath = "problems/#{probnum}"
    FileUtils.mkdir_p(destpath)
    File.open("#{destpath}/#{uploaded_main.original_filename}", 'wb') do |file|
      file.write(uploaded_main.read)
    end
    if uploaded_supp
      uploaded_supp.each do |upfile|
        File.open("#{destpath}/#{upfile.original_filename}", 'wb') do |file|
          file.write(upfile.read)
        end
      end
    end
    input = "#{sandhome}/input"
    output = "#{sandhome}/solutions"
    code = "#{sandhome}/code"
    sandbox = Docker::Container.create(
      'Image' => 'jje_sandbox:latest',
      'Volumes' => {input => {},
                    output => {}, 
                    code => {}}
    )
    sandbox.start('Binds' => ["#{probpath}/input:#{input}:ro", 
                               "#{probpath}/output:#{output}:ro", 
                               "#{ destpath}:#{code}:rw"],
                  'Cmd' => ["python3 grader.py #{sandhome}/code/#{uploaded_main.original_filename} #{uploaded_lang}"])
    # should return a value that we need to deal with.
    redirect_to @problem
    
  end

    # POST /problems/:id/submit/output
  def uploadOutput
    uploaded_output = params[:output]

    # TODO: handle submission
    sandhome = "/home/jjeuser"
    probnum = @problem.problem_id
    destpath = "users/#{current_user.user_id}/submissions/#{probnum}"
    probpath = "problems/#{probnum}"
    FileUtils.mkdir_p(destpath)
    File.open("#{destpath}/output", 'wb') do |file|
      file.write(uploaded_main.read)
    end

    output = "#{sandhome}/solutions"
    code = "#{sandhome}/code"
    sandbox = Docker::Container.create(
      'Image' => 'jje_sandbox:latest',
      'Volumes' => {"#{sandhome}/code" => {},
                    "#{sandhome}/output" => {}}
    )
    sandbox.start('Binds' => ["#{probpath}/output:#{output}:ro", 
                               "#{destpath}:#{code}:rw"],
                  'Cmd' => ["python3 grader.py --diff_files"])
    # should return a value that we need to deal with.
    redirect_to @problem
  end

  def downloadInput
    flname = File.basename(params[:flname])
    path = Rails.root.join("problems", "#{@problem.problem_id}", "input", flname)
    if File.exist?(path) then
      send_file path
    else
      raise ActionController::RoutingError, 'Input File Not Found'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    def problem_params
      params.require(:problem).permit(:name, :score, :description, files: {input: [], output: []})
    end
end

jje/app/helpers/problems_helper.rb
module ProblemsHelper
end

jje/app/views/problems/_form.html.erb
<%= form_for(problem) do |f| %>
  <% if problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% problem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :problem_id %>
    <%= f.text_field :problem_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :score %>
    <%= f.number_field :score %>
  </div>

  <div class="field">
    <%= f.label :problem_description %>
    <%= f.text_area :problem_description %>
  </div>

  <div class="field">
    <%= f.label :path %>
    <%= f.text_field :path %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jje/app/views/problems/edit.html.erb
<h1>Editing Problem</h1>

<script>
	var defaults = {
		createTokensOnBlur: true,
		delimiter: [' ', ',']
	}
	$(function() {
		$('.tokenfield#keywords_allkeywords').tokenfield(defaults);
		$('.tokenfield#tags_alltags').tokenfield(defaults);
	});
</script>

<%= form_for @problem, action: 'update', method: "put", html: {class: 'form-horizontal'} do |f| %>
	<div class="form-group">
		<%= f.label :name, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :name, required: true, class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :score, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.number_field :score, required: true, class: 'form-control', min: 0, step: 1 %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :description, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_area :description, required: true, class: 'form-control', rows: 3 %>
		</div>
	</div>

	<div class="form-group">
		<%= fields_for :keywords do |kw_f| %>
			<%= kw_f.label :allkeywords, class: 'col-sm-2 control-label' %>
			<div class="col-sm-10">
				<%= kw_f.text_field :allkeywords, class: 'form-control tokenfield', :'data-tokens' => @keywordstring %>
			</div>
		<% end %>
	</div>

	<div class="form-group">
		<%= fields_for :tags do |tags_f| %>
			<%= tags_f.label :alltags, class: 'col-sm-2 control-label' %>
			<div class="col-sm-10">
				<%= tags_f.text_field :alltags, class: 'form-control tokenfield', :'data-tokens' => @tagstring %>
			</div>
		<% end %>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit class: "btn btn-default" %>
		</div>
	</div>
<% end %>

<%= link_to 'Back', @problem %>

jje/app/views/problems/index.html.erb
<h1>Problems#index</h1>
<p>Find me in app/views/problems/index.html.erb</p>

jje/app/views/problems/new.html.erb
<h1>Create a new Problem</h1>

<script>
	var defaults = {
		createTokensOnBlur: true,
		delimiter: [' ', ',']
	}
	$(function() {
		$('.tokenfield#keywords_allkeywords').tokenfield(defaults);
		$('.tokenfield#tags_alltags').tokenfield(defaults);
	});
</script>


<%= form_for(@problem, url: {action: 'create'}, html: {class: 'form-horizontal', multipart: true}) do |f| %>
	<div class="form-group">
		<%= f.label :name, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :name, required: true, class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :score, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.number_field :score, required: true, class: 'form-control', min: 0, step: 1 %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :description, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_area :description, required: true, class: 'form-control', rows: 3 %>
		</div>
	</div>

	<div class="form-group">
		<%= fields_for :keywords do |kw_f| %>
			<%= kw_f.label :allkeywords, class: 'col-sm-2 control-label' %>
			<div class="col-sm-10">
				<%= kw_f.text_field :allkeywords, class: 'form-control tokenfield' %>
			</div>
		<% end %>
	</div>

	<div class="form-group">
		<%= fields_for :tags do |tags_f| %>
			<%= tags_f.label :alltags, class: 'col-sm-2 control-label' %>
			<div class="col-sm-10">
				<%= tags_f.text_field :alltags, class: 'form-control tokenfield' %>
			</div>
		<% end %>
	</div>

	<%= fields_for :files do |file_f| %>
	<div class="form-group">
		<%= file_f.label :input, "Input Files", class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= file_f.file_field(:input, required: true, multiple: true) %>
		</div>
	</div>
	<div class="form-group">
		<%= file_f.label :output, "Output Files", class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= file_f.file_field(:output, required: true, multiple: true) %>
		</div>
	</div>
	<% end %>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit class: "btn btn-default" %>
		</div>
	</div>
<% end %>

<%= link_to 'Back', :problems %>

jje/app/views/problems/show.html.erb
<span class="problem-page">
  <div class="panel problem-info">
    <p>
      <strong>Score:</strong>
      <%= @problem.score %>
    </p>
    
    <p>
      <strong>Solves:</strong>
      <%= @problem.solves %>
    </p>

    <p>
      <strong>Keywords:</strong>
      <% @problem.keywords.each do |kw| %>
        <span class="problem-keyword"><%= kw.keyword %></span>
      <% end %>
    </p>

    <% if user_signed_in? and current_user.admin then %>
      <p>
        <strong>Tags:</strong>
        <% @problem.tags.each do |tg| %>
          <span class="problem-tag"><%= tg.tag %></span>
        <% end %>
      </p>
    <% end %>

    <p>
      <strong>Input Files:</strong>
      <% if Dir.exist? @input_path then %>
        <% Dir.entries(@input_path).each do |fname| %>
          <% unless fname == '.' or fname == '..' %>
            <a href="/problems/<%= @problem.problem_id %>/inputs/<%= fname %>" download><%= fname %></a>
          <% end %>
        <% end %>
      <% else %>
        None
      <% end %>
    </p>
  </div>

  <div class="panel description">
    <div class="panel-heading problem-heading">
      <p>
        <strong>
          Problem #
          <%= @problem.problem_id %>:
        </strong>
          <%= @problem.name %>
      </p>
    </div>

    <div class="panel-body problem-description">
      <div class="descriptor">
        <p>
          <strong>Problem description</strong>
        </p>
      </div>

      <p>
        <%= @problem.description %>
      </p>
    </div>
  </div>
</span>

<div class="links">
<%= link_to 'Upload Solution', upload_problem_path(@problem) %> |
<% if user_signed_in? and current_user.admin then %>
<%= link_to('Edit (admin)', edit_problem_path(@problem)) %> |
<% end %>
<%= link_to 'Back', problems_path %>
</div>

<!-- <h3>Solved by</h3> -->
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Solve Date</th>
        </tr>
    </thead>
    <tbody>
        <% @solves.each do |prob| %>
        <tr>
            <td><%= link_to(prob.user.display_name, user_path(prob.user_id)) %></td>
            <td><%= prob.timestamp %></td>

        </tr>
        <% end %>
    </tbody>
</table>

jje/app/views/problems/showUpload.html.erb
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Upload Solution</h3>
        <h4 class="problem-name"><strong>Problem</strong> #<%= @problem.problem_id %>: <%= link_to(@problem.name, problem_path(@problem)) %></h4>
    </div>

    <div class="row container">
        <div class="col-md-6 center-text">
            <h3>Upload Code</h3>
            <%= form_tag(uploadCode_problem_path(@problem), method: "post", multipart: true) do %>
                <%= label_tag(:language, "Language") %>
                <%= select_tag(:language, options_for_select(TournamentLanguage::LanguageOptions)) %>

                <%= label_tag(:main, "Main File") %>
                <%= file_field_tag(:main) %>

                <%= label_tag('support[]', "Support Files") %>
                <%= file_field_tag('support[]', multiple: true) %>
                <hr />
                <%= submit_tag("Submit") %><%= submit_tag("Reset", { :name => 'reset', :type => 'reset' }) %>
            <% end %>

        </div>
        <div class="col-md-5 center-text">
            <h3>Upload Output</h3>
            <%= form_tag(uploadOutput_problem_path(@problem), method: "post", multipart: true) do %>
                <%= label_tag(:output, "Output") %>
                <%= file_field_tag(:output) %>
                <hr />
                <%= submit_tag("Submit") %>
          <% end %>
        </div>
    </div>
</div>