jje/config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new",      as: 'sign_in' # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    get "/edit_account" => "devise/registrations#edit", as: "edit_account"
    get "/sign_out"=> "devise/sessions#destroy",  as: 'sign_out'
  end

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  # contains only digits
  id_cnstrt = /\d+/
  # contains at least one non-digit
  nonid_cnst = /[^\/]*[^\d\/][^\/]*/


  root  'static_pages#Home'
  get   '/Home',          to: redirect('/'),            as: :home


  # Authorization
  get   '/auth/login',    to: 'static_pages#login'
  post  '/auth/login',    to: 'sessions#create',        as: 'login'
  get   '/auth/logout',   to: 'sessions#destroy',       as: 'logout'
  get   '/auth/register', to: 'static_pages#register',  as: 'register'
  post  '/auth/register', to: 'users#create',           as: :create_user
  get   '/auth/failure',  to: redirect('/auth/login?failed')
  get   '/auth/:provider/callback',  to: 'sessions#create'

  get   '/search',        to: 'static_pages#search',    as: :search

  # Subsection Homepages
  get   '/problems',    to: 'static_pages#problems',    as: :problems
  get   '/users',       to: 'static_pages#users',       as: :users
  get   '/tournaments', to: 'static_pages#tournaments', as: :tournaments

  # Problems Subsection
  get   '/problems/new',                to: 'problems#new',                           as: :new_problem
  post  '/problems',                    to: 'problems#create',                        as: :create_problem
  get   '/problems/statistics',         to: 'problems#stats',                         as: :stats_problem
  get   '/problems/:id',                to: 'problems#show',          id: id_cnstrt,  as: :problem
  get   '/problems/:id/edit',           to: 'problems#edit',          id: id_cnstrt,  as: :edit_problem
  put   '/problems/:id',                to: 'problems#update',        id: id_cnstrt,  as: :update_problem
  get   '/problems/:id/submit/',        to: 'problems#showUpload',    id: id_cnstrt,  as: :upload_problem
  post  '/problems/:id/submit/code',    to: 'problems#uploadCode',    id: id_cnstrt,  as: :uploadCode_problem
  post  '/problems/:id/submit/output',  to: 'problems#uploadOutput',  id: id_cnstrt,  as: :uploadOutput_problem
  get   '/problems/:id/inputs/*flname', to: 'problems#downloadInput', id: id_cnstrt,  as: :downloadInput_problem, format: false

  # Users Subsection
  get   '/users/:id',                   to: 'users#show',             id: id_cnstrt,  as: :user
  get   '/users/:id/edit',              to: 'users#edit',             id: id_cnstrt,  as: :edit_user
  patch '/users/:id',                   to: 'users#update',           id: id_cnstrt,  as: :update_user
  get   '/users/:id/submissions',       to: 'users#submissions',      id: id_cnstrt,  as: :user_submissions
  get   '/users/:user_id/submissions/:problem_id/:timestamp', to: 'user_submissions#show',  user_id: id_cnstrt, problem_id: id_cnstrt, as: :user_submission
  match '/users/:username/(*all)',      to: 'users#name_to_id', username: nonid_cnst, via: [:get, :put]

  # Tournaments Subsection
  get   '/tournaments/new',             to: 'tournaments#new',                        as: :new_tournament
  post  '/tournaments',                 to: 'tournaments#create',                     as: :create_tournament
  get   '/tournaments/:id',             to: 'tournaments#show',     id: id_cnstrt,    as: :tournament
  get   '/tournaments/:id/edit',        to: 'tournaments#edit',     id: id_cnstrt,    as: :edit_tournament
  patch   '/tournaments/:id',             to: 'tournaments#update',   id: id_cnstrt,    as: :update_tournament
  get   '/tournaments/:id/statistics',  to: 'tournaments#stats',    id: id_cnstrt,    as: :stats_tournament
  get   '/tournaments/:id/join',        to: 'tournaments#join',     id: id_cnstrt,    as: :join_tournament

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

jje/app/models/tournament.rb
class Tournament < ApplicationRecord
  self.primary_key = 'tournament_id'
  has_many :languages, :class_name => 'TournamentLanguage'
  has_many :contains
  has_many :problems, through: :contains
  has_many :competes_ins
  has_many :users, through: :competes_ins

  accepts_nested_attributes_for :languages
end

jje/app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy, :join]
  before_action :set_tournament, only: [:show, :edit, :update, :destroy, :join]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
  end

  # GET /tournaments/new
  def new
    unless current_user.admin?
      redirect_to :tournaments, flash: {error: 'Only administrators can create new tournaments.'}
      return
    end
    @tournament = Tournament.new
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    unless current_user.admin?
      redirect_to :tournaments, flash: {error: 'Only administrators can create new tournaments.'}
      return
    end

    @tournament = Tournament.new(tournament_params)

    if @tournament.save
      # now create the TournamentLanguages
      TournamentLanguage::LanguageOptions.each do |(name, key)|
        if params['languages'][key] == "1"
          TournamentLanguage.create(language: name, tournament_id: @tournament.tournament_id)
        end
      end
      redirect_to @tournament, flash: {success: 'Tournament was created!'}
    else
      redirect_to @tournament, flash: {error: "Failed to create tournament: #{@tournament.errors.full_messages}"}
    end
  end

  # GET /tournaments/1/edit
  def edit
    unless current_user.admin?
      redirect_to :tournament, flash: {error: 'Only administrators can edit tournaments.'}
      return
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    unless current_user.admin?
      redirect_to @tournament, flash: {error: 'Only administrators can edit tournaments.'}
      return
    end

    Problem.where(problem_id: params[:problem_id]).each do |prob|
      unless Contain.exists?(tournament_id: @tournament.tournament_id, problem_id: prob.problem_id)
        contain = Contain.create(tournament_id: @tournament.tournament_id, problem_id: prob.problem_id)
      end
    end

    if @tournament.update(tournament_params)
      redirect_to :edit_tournament, flash: {success: 'Tournament was successfully updated.'}
    else
      redirect_to @tournament, flash: {error: "Failed to edit tournament: #{@tournament.errors.full_messages}"}
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    unless current_user.admin?
      redirect_to @tournament, flash: {error: 'Only administrators can delete tournaments.'}
      return
    end
    if @tournament.destroy
      redirect_to :tournaments, flash: {success: 'Tournament was successfully destroyed.'}
    else
      redirect_to @tournament, flash: {error: "Failed to delete tournament: #{@tournament.errors.full_messages}"}
    end
  end

  # GET /tournaments/1/join
  def join
    if @tournament.end < DateTime.current() then
      flash[:error] = "This tournament is already over."
    elsif CompetesIn.find_by(tournament_id: @tournament.tournament_id, user_id: current_user.user_id)
      flash[:notice] = "You're already in the tournament!"
    elsif CompetesIn.create(tournament_id: @tournament.tournament_id, user_id: current_user.user_id)
      flash[:success] = "You joined the tournament!"
    else
      flash[:error] = "An error occurred while joining."
    end
    redirect_to @tournament
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :start, :end, :problems, :languages, 'start(1i)', 'start(2i)', 'start(3i)', 'start(4i)', 'start(5i)',
                                                'end(1i)',   'end(2i)',   'end(3i)',   'end(4i)',   'end(5i)')
    end
end

jje/app/helpers/tournaments_helper.rb
module TournamentsHelper
end

jje/app/views/tournaments/_form.html.erb
<%= form_for(tournament) do |f| %>
  <% if tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>


  <div class="field">
    <%= f.label :start %>
    <%= f.text_field :start %>
  </div>

  <div class="field">
    <%= f.label :end %>
    <%= f.text_field :end %>
  </div>


  <h3> Problems </h3>

  <table class="table table-striped">
      <thead>
          <tr>
              <th>id</th>
              <th>name</th>
          </tr>
      </thead>
      <tbody>
          <% tournament.problems.each do |prob| %>
            <tr>
                <td><%= prob.id %></td>
                <td><%= prob.name %></td>
            </tr>
          <% end %>

          <tr>
            <td>
                <form accept-charset="UTF-8" action="/tournaments" method="patch">
                  <input type="int" name="problem_id" value="" />
            </td>
            <td>
              
            </td>
          </tr>
      </tbody>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

jje/app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form', tournament: @tournament %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

jje/app/views/tournaments/index.html.erb
<h1>Tournaments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= link_to 'Show', tournament %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament', new_tournament_path %>

jje/app/views/tournaments/new.html.erb
<h1>Create a new Tournament</h1>

<%= form_for @tournament, url: {action: 'create'}, html: {class: 'form-horizontal'} do |f| %>
	<div class="form-group">
		<%= f.label :name, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :name, class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :start, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.datetime_select :start, class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :end, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.datetime_select :end, class: 'form-control' %>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-offset-2 col-sm-10">
			<h4>Languages</h4>
		</div>
	</div>
	<div class="form-group">
	<%= fields_for :languages  do |langs_f| %>
		<% (TournamentLanguage::LanguageOptions).each do |(name, key)| %>
			<div class="col-sm-offset-2 col-sm-10">
				<div class="checkbox">
					<label>
						<%= langs_f.check_box("#{key}") %> <%= "#{name}" %>
					</label>
				</div>
			</div>
		<% end %>
	<% end %>
	</div>

	<br />
	<%= f.submit %>
<% end %>

<%= link_to 'Back', :tournaments %>

jje/app/views/tournaments/show.html.erb
<div class="panel tournament">
    <div class="panel-heading tournament-heading">
        <p>
            <strong>Tournament 
            #<%= @tournament.tournament_id %>:
            </strong>
        <%= @tournament.name %>
        </p>
    </div>

    <div class="tournament-body">
        <p>
            <strong>Starts:</strong>
            <%= @tournament.start ? @tournament.start.getlocal.to_s(:long) : "" %>
        </p>

        <p>
            <strong>Ends:</strong>
            <%= @tournament.end ? @tournament.end.getlocal.to_s(:long) : "" %>
        </p>

        <p>
            <strong>Status:</strong>
            <%= (@tournament.end < DateTime.current ? 'over' : (@tournament.start < DateTime.current ? 'active' : 'not yet')) %>
        </p>

        <p>
            <strong>Languages:</strong>
            <% for tourney_lang in TournamentLanguage.where(tournament_id: @tournament.tournament_id) do %>
                <span class="tournament-language"><%= tourney_lang.language %></span>
            <% end %>
        </p>

        <p>
            <strong>Participants:</strong>
            <%= CompetesIn.where(tournament_id: @tournament.tournament_id).count %>
        </p>
    </div>
</div>

<% if DateTime.current > @tournament.start then %>
    <h3> Problems </h3>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Score</th>
            </tr>
        </thead>
        <tbody>
          <% @tournament.problems.each do |prob| %>
            <tr>
                <td><%= link_to(prob.name, problem_path(prob.problem_id)) %></td>
                <td><%= prob.score %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
<% end %>

<% if user_signed_in? then %>
    <%= link_to('Join!', join_tournament_path(@tournament)) %> |

    <% if current_user().admin then %>
        <%= link_to('Edit (admin)', edit_tournament_path(@tournament)) %> |
    <% end %>
<% end %>

<%= link_to 'Back', tournaments_path %>