jje/config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new",      as: 'sign_in' # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    get "/edit_account" => "devise/registrations#edit", as: "edit_account"
    get "/sign_out"=> "devise/sessions#destroy",  as: 'sign_out'
  end

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  # contains only digits
  id_cnstrt = /\d+/
  # contains at least one non-digit
  nonid_cnst = /[^\/]*[^\d\/][^\/]*/


  root  'static_pages#Home'
  get   '/Home',          to: redirect('/'),            as: :home


  # Authorization
  get   '/auth/login',    to: 'static_pages#login'
  post  '/auth/login',    to: 'sessions#create',        as: 'login'
  get   '/auth/logout',   to: 'sessions#destroy',       as: 'logout'
  get   '/auth/register', to: 'static_pages#register',  as: 'register'
  post  '/auth/register', to: 'users#create',           as: :create_user
  get   '/auth/failure',  to: redirect('/auth/login?failed')
  get   '/auth/:provider/callback',  to: 'sessions#create'

  get   '/search',        to: 'static_pages#search',    as: :search

  # Subsection Homepages
  get   '/problems',    to: 'static_pages#problems',    as: :problems
  get   '/users',       to: 'static_pages#users',       as: :users
  get   '/tournaments', to: 'static_pages#tournaments', as: :tournaments

  # Problems Subsection
  get   '/problems/new',                to: 'problems#new',                           as: :new_problem
  post  '/problems',                    to: 'problems#create',                        as: :create_problem
  get   '/problems/statistics',         to: 'problems#stats',                         as: :stats_problem
  get   '/problems/:id',                to: 'problems#show',          id: id_cnstrt,  as: :problem
  get   '/problems/:id/edit',           to: 'problems#edit',          id: id_cnstrt,  as: :edit_problem
  put   '/problems/:id',                to: 'problems#update',        id: id_cnstrt,  as: :update_problem
  get   '/problems/:id/submit/',        to: 'problems#showUpload',    id: id_cnstrt,  as: :upload_problem
  post  '/problems/:id/submit/code',    to: 'problems#uploadCode',    id: id_cnstrt,  as: :uploadCode_problem
  post  '/problems/:id/submit/output',  to: 'problems#uploadOutput',  id: id_cnstrt,  as: :uploadOutput_problem
  get   '/problems/:id/inputs/*flname', to: 'problems#downloadInput', id: id_cnstrt,  as: :downloadInput_problem, format: false

  # Users Subsection
  get   '/users/:id',                   to: 'users#show',             id: id_cnstrt,  as: :user
  get   '/users/:id/edit',              to: 'users#edit',             id: id_cnstrt,  as: :edit_user
  patch '/users/:id',                   to: 'users#update',           id: id_cnstrt,  as: :update_user
  get   '/users/:id/submissions',       to: 'users#submissions',      id: id_cnstrt,  as: :user_submissions
  get   '/users/:user_id/submissions/:problem_id/:timestamp', to: 'user_submissions#show',  user_id: id_cnstrt, problem_id: id_cnstrt, as: :user_submission
  match '/users/:username/(*all)',      to: 'users#name_to_id', username: nonid_cnst, via: [:get, :put]

  # Tournaments Subsection
  get   '/tournaments/new',             to: 'tournaments#new',                        as: :new_tournament
  post  '/tournaments',                 to: 'tournaments#create',                     as: :create_tournament
  get   '/tournaments/:id',             to: 'tournaments#show',     id: id_cnstrt,    as: :tournament
  get   '/tournaments/:id/edit',        to: 'tournaments#edit',     id: id_cnstrt,    as: :edit_tournament
  patch   '/tournaments/:id',             to: 'tournaments#update',   id: id_cnstrt,    as: :update_tournament
  get   '/tournaments/:id/statistics',  to: 'tournaments#stats',    id: id_cnstrt,    as: :stats_tournament
  get   '/tournaments/:id/join',        to: 'tournaments#join',     id: id_cnstrt,    as: :join_tournament

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

jje/app/controllers/static_pages_controller.rb
INDEX_PAGE_SIZE = 10

class StaticPagesController < ApplicationController

  def Home
    @homepage_users = User.limit(6).order(score: :desc)
    @easiest_problems = Problem.limit(6).order(score: :asc)
    @now = DateTime.current()
    @least_solved_problems = Problem.limit(6).order(solves: :asc)
    @homepage_tourneys = Tournament.limit(6)
  end

  def users
    @top_users = User.limit(10).order(score: :desc)
    @users = do_paging(User)
  end

  def problems
    @problems = do_paging(Problem)
  end

  def tournaments
    @now = DateTime.current()
    @tourneys = do_paging(Tournament)
  end

  def search
    if params[:q] and params[:q].length > 0 then
      @results = []
      @problem_result
      params[:q].split(" ").each do |word|
        @name_results = Problem.where('lower(name) LIKE ?', "%#{word}%".downcase)
        @name_results.each do |result|
          @results.push(result)
        end
        @keyword_results = ProblemKeyword.where('lower(keyword) LIKE ?', "%#{word}%".downcase)
        @keyword_results.each do |result|
          @results.push(result.problem)
        end
        if user_signed_in?
          if current_user.admin
            @tag_results = ProblemTag.where('lower(tag) LIKE ?', "%#{word}%".downcase)
            @tag_results.each do |result|
              @results.push(result.problem)
            end
          end
        end
      end
      if @results.length > 0 then
        @results = @results.uniq{|x| x.problem_id}
      end
    end
  end

  private
    def do_paging (pagetype)
      @pg_count = (pagetype.count / INDEX_PAGE_SIZE.to_f).ceil
      @pg = (params["pg"] || 1).to_i

      if @pg_count == 0
        return []
      elsif @pg < 1
        @pg = 1
      elsif @pg > @pg_count
        @pg = @pg_count
      end

      return pagetype.limit(INDEX_PAGE_SIZE).offset(INDEX_PAGE_SIZE * (@pg - 1))
    end
end

jje/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

jje/app/views/static_pages/Home.html.erb
<h1>Welcome to J²E</h1>

	<div class="welcome">
		<h2>About Us</h2>
		<p> J²E is an online programming judge. </p>
		<p> The purpose of this website is to allow a user to practice their programming skills.  In order to do so there are problems found on this website that a user can attempt to code a solution to and submit it for grading.  If the answer is correct the user's score will increase, if not then the user will be notified that there is a problem with their code. </p>
	</div>


	<div class="clearfix">
		<div class="col-md-6">
			<div class="page-headline clearfix">
				<h3> Top Users </h3>
			</div>

			<table class="table table-striped rankings">
				<thead>
					<tr>
						<th> Rank </th>
						<th> Name </th>
						<th> Score </th>
					</tr>
				</thead>
				<tbody>
					<% @homepage_users.each_with_index do |user, index| %>
					<tr>
						<td><%= index %></td>
						<td><%= link_to(user.display_name, user_path(user.user_id)) %></td>
						<td><%= user.score %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>

		<div class="col-md-6">
			<div class="page-headline clearfix">
				<h3> Easiest Problems </h3>
			</div>

			<table class="table table-striped problems">
				<thead>
					<tr>
						<th> ID </th>
						<th> Name </th>
						<th> Score </th>
						<th> Solves </th>
					</tr>
				</thead>
				<tbody>
					<% @easiest_problems.each do |prob| %>
					<tr>
						<td><%= prob.problem_id %></td>
						<td><%= link_to(prob.name, problem_path(prob.problem_id)) %></td>
						<td><%= prob.score %></td>
						<td><%= prob.solves %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>

		<div class="col-md-6">
			<div class="page-headline">
				<h3> Least Solved Problems </h3>
			</div>

			<table class="table table-striped hard-problems">
				<thead>
					<tr>
						<th> ID </th>
						<th> Name </th>
						<th> Score </th>
						<th> Solves </th>
					</tr>
				</thead>
				<tbody>
					<% @least_solved_problems.each do |prob| %>
					<tr>
						<td><%= prob.problem_id %></td>
						<td><%= link_to(prob.name, problem_path(prob.problem_id)) %></td>
						<td><%= prob.score %></td>
						<td><%= prob.solves %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>

		<span class="col-md-6">
			<div class="page-headline">
				<h3> Active Tournaments </h3>
			</div>

			<table class="table table-striped tournaments">
				<thead>
					<tr>
						<th> # </th>
						<th> Tournament </th>
						<th> Started </th>
						<th> Ends </th>
						<th> Active? </th>
					</tr>
				</thead>
				<tbody>
					<% @homepage_tourneys.each do |tourney| %>
					<tr>
						<td><%= tourney.tournament_id %></td>
						<td><%= tourney.name %></td>
						<td><%= tourney.start %></td>
						<td><%= tourney.end %></td>
						<td><%= (tourney.end < @now ? 'over' : (tourney.start < @now ? 'active' : 'not yet')) %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</span>
	</div>

jje/app/views/static_pages/login.html.erb
<div class="panel panel-info">
    <div class="panel-heading">
        <h2 class="panel-title">Please Log In</h2>
    </div>

    <div class="row container">
        <div class="col-md-5 center-text">
            <h3>with OAuth</h3>
            <hr />
            <form method="get" action="<%= request.protocol + request.host_with_port %>/users/auth/google_oauth2">
                <button type="submit"><%= image_tag("oauth/btn_google_dark.svg", class: "login_btn_icon") %> Google</button>
            </form>
            <form method="get" action="https://github.com/login/oauth/authorize">
                <input type="hidden" name="client_id" value="">
                <input type="hidden" name="redirect_uri" value="<%= request.protocol + request.host_with_port %>/auth/github/callback">
                <input type="hidden" name="scope" value="user">
                <button type="submit"><%= image_tag("oauth/GitHub-Mark-120px-dark.png", class: "login_btn_icon") %> GitHub</button>
            </form>

        </div>

        <div class="col-md-7" style="border-left: 1px solid">
            <h3 class="center-text">with credentials</h3>
            <hr />
            <!--<form class="form-horizontal">
                <fieldset>
                    <input id="username-input" name="username" type="text" placeholder="Username" class="form-control input-md">
                    <div class="spacing"><input type="checkbox" name="checkboxes" id="checkboxes-0" value="1"><small>Remember Me</small></div>
                    <input id="password-input" name="password" type="password" class="form-control input-md">
                    <div class="spacing"><a href="#"><small>Forgot Password?</small></a><br /></div>
                    <button id="login-submit" name="login-submit" class="btn btn-info btn-sm pull-right">Log In</button>
                </fieldset>
            </form>-->
            <%= form_for(:session, url: :login, method: "post", class: "form-horizontal ") do |f| %>
                <%= f.label :username %>
                <%= f.text_field :username, class: 'form-control' %>

                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
                <%= f.submit "Log in", class: "btn btn-primary pull-right" %>
            <% end %>
        </div>
    </div>
    <div class="panel-footer">
        <h4>...or <%= link_to("register", register_url) %> a new account.</h4>
    </div>
</div>

jje/app/views/static_pages/problems.html.erb
<h1>Problems Page</h1>

<article class="problems">
	<% if user_signed_in? and current_user.admin then %>
	<section class="create-problem">
		<h4>Problem Creation</h4>
		<p class="create-new"><%= link_to('Create a New Problem (admin)', :new_problem) %></p>
	</section>
	<% end %>
	<section>
		<h3>All Problems<%=
			if @pg_count > 1
				render inline: " <small>(#{@pg} of #{@pg_count})</small>"
			end
		%></h3>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>ID</th>
					<th>Name</th>
					<th>Value</th>
					<th>Solves</th>
				</tr>
			</thead>
			<tbody>
				<% @problems.each do |prob| %>
				<tr>
					<td><%= prob.problem_id %></td>
					<td><%= link_to(prob.name, problem_path(prob.problem_id)) %></td>
					<td><%= prob.score %></td>
					<td><%= prob.solves %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<%= render partial: 'shared/paginator', locals: { pg: @pg, pg_count: @pg_count } %>
	</section>
</article>

jje/app/views/static_pages/register.html.erb
<h1>Creating an Account</h1>
<p>Just creating the pages needed for the website</p>

jje/app/views/static_pages/search.html.erb
<article>
	<section>
		<h3>Search</h3>
		<%= form_tag(:search, method: 'get', id: "search-form") do %>
			<div class="input-group">
				<%= text_field_tag :q, params[:q], class: 'form-control' %>
				<span class="input-group-btn">
					<button class="btn btn-default" type="submit">Search</button>
				</span>
			</div>
		<% end %>

	</section>
	<% if @results then %>
		<section>
			<h3>Search Results (problems)</h3>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>ID</th>
						<th>Name</th>
						<th>Value</th>
					</tr>
				</thead>
				<tbody>
					<% @results.each do |prob| %>
					<tr>
						<td><%= prob.problem_id %></td>
						<td><%= link_to(prob.name, problem_path(prob.problem_id)) %></td>
						<td><%= prob.score %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</section>
	<% end %>
</article>

jje/app/views/static_pages/tournaments.html.erb
<h1>Tournaments</h1>

<article class="tournaments">
	<% if user_signed_in? and current_user.admin then %>
	<section class="create-tournament">
		<h4>Tournament Creation</h4>
		<%= link_to('Create a New Tournament (admin)', :new_tournament) %>
	</section>
	<% end %>
	<section>
		<h3>All Tournaments<%=
			if @pg_count > 1
				render inline: " <small>(#{@pg} of #{@pg_count})</small>"
			end
		%></h3>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>ID</th>
					<th>Name</th>
					<th>Starts</th>
					<th>Ends</th>
					<th>Status</th>
					<th>Participants</th>
					<th>Languages</th>
				</tr>
			</thead>
			<tbody>
				<% @tourneys.each do |tourney| %>
				<tr>
					<td><%= tourney.tournament_id %></td>
					<td><%= link_to(tourney.name, tournament_path(tourney.tournament_id)) %></td>
					<td><%= tourney.start.getlocal.to_s(:long) %></td>
					<td><%= tourney.end.getlocal.to_s(:long) %></td>
					<td><%= (tourney.end < @now ? 'over' : (tourney.start < @now ? 'active' : 'not yet')) %></td>
					<td><%= CompetesIn.where(tournament_id: tourney.tournament_id).count %></td>
					<td>
					<% for tourney_lang in TournamentLanguage.where(tournament_id: tourney.tournament_id) do %>
						<span class="tournament-language"><%= tourney_lang.language %></span>
					<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<%= render partial: 'shared/paginator', locals: { pg: @pg, pg_count: @pg_count } %>
	</section>
</article>

jje/app/views/static_pages/user_account.erb
<h1> User Account </h1>

<article>
	<section>
		
	</section>
</article>

jje/app/views/static_pages/users.html.erb
<h1>Users Page</h1>

<article>
	<section>
		<h3>Top Users</h3>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Rank</th>
					<th>User</th>
					<th>University</th>
					<th>Company</th>
					<th>Score</th>
				</tr>
			</thead>
			<tbody>
				<% @top_users.each_with_index do |user, index| %>
				<tr>
					<td><%= index + 1 %></td>
					<td><%= link_to(user.display_name, user_path(user.user_id)) %></td>
					<td><%= user.university %></td>
					<td><%= user.company %></td>
					<td><%= user.score %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</section>
	<section>
		<h3>All Users<%=
			if @pg_count > 1
				render inline: " <small>(#{@pg} of #{@pg_count})</small>"
			end
		%></h3>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>ID</th>
					<th>User</th>
					<th>University</th>
					<th>Company</th>
					<th>Score</th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= user.user_id %></td>
					<td><%= link_to(user.display_name, user_path(user.user_id)) %></td>
					<td><%= user.university %></td>
					<td><%= user.company %></td>
					<td><%= user.score %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<%= render partial: 'shared/paginator', locals: { pg: @pg, pg_count: @pg_count } %>
	</section>
</article>